import { expect, test } from "@playwright/test"

test("Compass drawer reveals on demand, preserves scroll space, and remembers its pin", async ({ page, baseURL, isMobile, browserName, headless }, testInfo) => {
  test.skip(Boolean(process.env.PLAYWRIGHT_BASE_URL), "Uses the isolated local demo workspace.")
  if (!baseURL) throw new Error("A local URL is required.")
  await page.context().addCookies([{ name: "compass-demo", value: "true", url: baseURL }])
  if (!isMobile) await page.setViewportSize({ width: 1024, height: 600 })
  await page.goto("/dashboard/help/navigating-projects")
  if (isMobile) await page.getByRole("button", { name: "Open menu", exact: true }).click()
  const root = page.locator('[data-slot="sidebar-workspace-drawer"]:visible')
  const panel = root.getByRole("region", { name: "Compass drawer", includeHidden: true })
  const trigger = root.locator('button[aria-controls]').first()
  const sidebar = isMobile ? page.locator('[data-sidebar="sidebar"][data-mobile="true"]') : page.locator('[data-slot="sidebar-inner"]')
  const nav = sidebar.locator('[data-slot="sidebar-content"]')
  const initialHeight = await nav.evaluate((element) => element.clientHeight)
  await expect(root).toHaveAttribute("data-open", "false")
  await expect(panel).toHaveAttribute("inert", "")

  if (!isMobile) {
    await trigger.hover()
    await expect(root).toHaveAttribute("data-open", "true")
    expect(await nav.evaluate((element) => element.clientHeight)).toBe(initialHeight)
    await page.mouse.move(850, 200)
    await expect(root).toHaveAttribute("data-open", "false")
  }
  await trigger.click()
  await expect(root).toHaveAttribute("data-open", "true")
  const photo = root.getByRole("button", { name: "Edit sidebar photo", exact: true })
  await expect(photo).toBeVisible()
  await expect(root.getByRole("button", { name: "Feedback", exact: true })).toBeVisible()
  await expect(root.getByRole("link", { name: "Settings", exact: true })).toHaveAttribute("href", "/dashboard/settings")
  const photoStyle = await photo.evaluate((element) => ({ radius: getComputedStyle(element.firstElementChild ?? element).borderRadius, shadow: getComputedStyle(element).boxShadow, mask: getComputedStyle(element.firstElementChild ?? element).maskImage }))
  expect(photoStyle).toEqual({ radius: "0px", shadow: "none", mask: "none" })
  await root.getByRole("button", { name: "Pin Compass drawer open", exact: true }).click()
  await expect(root).toHaveAttribute("data-pinned", "true")
  expect(await nav.evaluate((element) => element.clientHeight)).toBeLessThan(initialHeight)
  // Firefox headless injects hidden-scrollbar CSS; native bars are checked headed.
  if (browserName !== "firefox" || !headless) expect(await nav.evaluate((element) => getComputedStyle(element).getPropertyValue("scrollbar-width"))).not.toBe("none")
  await page.reload()
  if (isMobile) await page.getByRole("button", { name: "Open menu", exact: true }).click()
  await expect(root).toHaveAttribute("data-pinned", "true")
  await expect(photo).toBeVisible()
  await photo.click()
  await expect(page.getByRole("button", { name: "Change photo", exact: true })).toBeVisible()
  await expect(page.getByRole("button", { name: "Reset", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Change photo", exact: true }).press("Escape")
  await expect(root).toHaveAttribute("data-open", "true")
  await root.getByRole("button", { name: "Unpin Compass drawer", exact: true }).click()
  await expect(root).toHaveAttribute("data-pinned", "false")
  await root.getByRole("button", { name: "Pin Compass drawer open", exact: true }).press("Escape")
  await expect(root).toHaveAttribute("data-open", "false")
  await trigger.press("Enter")
  await expect(root).toHaveAttribute("data-open", "true")
  await trigger.press("ArrowUp")
  await expect(photo).toBeFocused()
  await photo.press("Escape")
  await expect(root).toHaveAttribute("data-open", "false")
  await expect(trigger).toBeFocused()
  await page.reload()
  if (isMobile) await page.getByRole("button", { name: "Open menu", exact: true }).click()
  await expect(root).toHaveAttribute("data-pinned", "false")
  await expect(root).toHaveAttribute("data-open", "false")
  if (!isMobile) {
    await page.getByRole("button", { name: "Collapse sidebar", exact: true }).click()
    await trigger.click()
    await expect(photo).toBeVisible()
    await photo.press("Escape")
    await expect(root).toHaveAttribute("data-open", "false")
  }
  await page.screenshot({ path: testInfo.outputPath("quiet-compass-drawer.png") })
})

for (const audience of ["owner", "sub-vendor"]) {
  test(`${audience} workspace preserves project navigation and personal controls`, async ({ page, baseURL, isMobile }, testInfo) => {
    test.skip(Boolean(process.env.PLAYWRIGHT_BASE_URL), "Uses the isolated local demo workspace.")
    if (!baseURL) throw new Error("A local URL is required.")
    await page.context().addCookies([{ name: "compass-demo", value: "true", url: baseURL }])
    if (!isMobile) await page.setViewportSize({ width: 1024, height: 600 })
    await page.goto(`/preview/projects/e2e-project-001/${audience}`)
    const nav = page.getByRole("navigation", { name: "Project workspace", exact: true }).filter({ visible: true })
    await expect(nav.getByRole("link", { name: "Dashboard", exact: true })).toHaveAttribute("href", `/preview/projects/e2e-project-001/${audience}`)
    const root = page.locator('[data-slot="sidebar-workspace-drawer"]:visible')
    if (isMobile) {
      await expect(root).toHaveCount(0)
      await page.getByRole("button", { name: "Notification settings", exact: true }).click()
      await expect(page.getByRole("dialog").getByRole("heading", { name: "Notification settings", exact: true })).toBeVisible()
      return
    }
    const navHeight = await nav.evaluate((element) => element.clientHeight)
    await expect(root).toHaveAttribute("data-open", "false")
    await root.getByRole("button", { name: "Open Compass drawer", exact: true }).click()
    await expect(root.getByRole("button", { name: "Notifications", exact: true })).toBeVisible()
    await expect(root.getByRole("link", { name: "Settings", exact: true })).toHaveCount(0)
    await expect(root.getByRole("button", { name: "Open Office Talk", exact: true })).toHaveCount(0)
    await root.getByRole("button", { name: "Appearance", exact: true }).click()
    await expect(page.getByRole("button", { name: "Light", exact: true })).toBeVisible()
    await expect(page.getByRole("button", { name: "Dark", exact: true })).toBeVisible()
    await page.getByRole("button", { name: "Light", exact: true }).press("Escape")
    await expect(root).toHaveAttribute("data-open", "true")
    await root.getByRole("button", { name: "Pin Compass drawer open", exact: true }).click()
    expect(await nav.evaluate((element) => element.clientHeight)).toBeLessThan(navHeight)
    await page.reload()
    await expect(root).toHaveAttribute("data-pinned", "true")
    await root.getByRole("button", { name: "Edit sidebar photo", exact: true }).click()
    await expect(page.getByRole("button", { name: "Change photo", exact: true })).toBeVisible()
    await expect(page.getByRole("button", { name: "Reset", exact: true })).toBeVisible()
    await page.getByRole("button", { name: "Change photo", exact: true }).press("Escape")
    const lastLink = nav.getByRole("link").last()
    await lastLink.scrollIntoViewIfNeeded()
    await expect(lastLink).toBeInViewport()
    await page.screenshot({ path: testInfo.outputPath(`${audience}-pinned-drawer.png`) })
  })
}
