import { expect, test } from "@playwright/test"

test("expanded project groups keep financial links reachable after nested menus grow", async ({ page, baseURL }, testInfo) => {
  test.skip(Boolean(process.env.PLAYWRIGHT_BASE_URL), "Uses the isolated local demo workspace.")
  test.skip(testInfo.project.name.startsWith("mobile"), "Covers the desktop sidebar's nested height animation.")
  if (!baseURL) throw new Error("A local URL is required.")
  await page.context().addCookies([{ name: "compass-demo", value: "true", url: baseURL }])
  await page.setViewportSize({ width: 1024, height: 600 })
  await page.goto("/dashboard/help/navigating-projects")
  await page.getByRole("button", { name: "Open Compass drawer", exact: true }).click()
  await page.getByRole("button", { name: "Pin Compass drawer open", exact: true }).click()
  const photo = page.getByRole("button", { name: "Edit sidebar photo", exact: true })
  await expect(photo).toBeVisible()
  const sidebar = page.locator('[data-slot="sidebar-inner"]')
  const sidebarWidth = await sidebar.evaluate((element) => element.getBoundingClientRect().width)
  const sidebarHeight = await sidebar.evaluate((element) => element.getBoundingClientRect().height)
  expect(await photo.evaluate((element) => element.getBoundingClientRect().width)).toBeLessThan(sidebarWidth * 0.7)
  const photoHeight = await photo.evaluate((element) => element.getBoundingClientRect().height)
  expect(photoHeight).toBeLessThan(sidebarHeight / 4)
  await page.getByRole("separator", { name: "Resize sidebar" }).focus()
  await page.getByRole("separator", { name: "Resize sidebar" }).press("ArrowRight")
  await expect.poll(() => sidebar.evaluate((element) => element.getBoundingClientRect().width)).toBeGreaterThan(sidebarWidth)
  expect(await photo.evaluate((element) => element.getBoundingClientRect().height)).toBe(photoHeight)
  const projects = page.getByRole("button", { name: "Projects", exact: true })
  await projects.click()
  const contentId = await projects.getAttribute("aria-controls")
  if (!contentId) throw new Error("The Projects menu must identify its content.")
  const content = page.locator(`[id="${contentId}"]`)
  // Wait for the opening animation to finish before growing its nested content.
  await page.waitForTimeout(200)
  for (const title of ["Updates & Logs", "Project Records", "Planning & Procurement", "Project Financials"]) {
    await page.getByRole("button", { name: title, exact: true }).click()
    await expect.poll(() => content.evaluate((element) => element.scrollHeight - element.clientHeight)).toBeLessThanOrEqual(1)
  }
  const financials = page.getByRole("button", { name: "Project Financials", exact: true })
  const budget = page.getByRole("link", { name: "Project Budget", exact: true })
  await budget.scrollIntoViewIfNeeded()
  await expect(budget).toBeInViewport()
  // Hit testing checks clipping ancestors as well as the link's viewport bounds.
  await expect.poll(() => budget.evaluate((element) => {
    const rect = element.getBoundingClientRect()
    return element.contains(document.elementFromPoint(rect.x + rect.width / 2, rect.y + rect.height / 2))
  })).toBe(true)
  await page.screenshot({ path: testInfo.outputPath("reachable-financial-menu.png") })
  for (let attempt = 0; attempt < 3; attempt += 1) {
    await financials.click()
    await expect(financials).toHaveAttribute("aria-expanded", "false")
    await financials.click()
    await expect(financials).toHaveAttribute("aria-expanded", "true")
    await expect.poll(() => content.evaluate((element) => element.scrollHeight - element.clientHeight)).toBeLessThanOrEqual(1)
  }
  await budget.focus()
  await budget.press("Enter")
  await expect(page).toHaveURL(/\/dashboard\/projects\/select\?target=budget/)
})

test("the mobile sidebar keeps its photo compact and Financials accessible", async ({ page, baseURL }, testInfo) => {
  test.skip(Boolean(process.env.PLAYWRIGHT_BASE_URL), "Uses the isolated local demo workspace.")
  test.skip(!testInfo.project.name.startsWith("mobile"), "Covers the mobile sidebar sheet.")
  if (!baseURL) throw new Error("A local URL is required.")
  await page.context().addCookies([{ name: "compass-demo", value: "true", url: baseURL }])
  await page.goto("/dashboard/help/navigating-projects")
  await page.getByRole("button", { name: "Open menu", exact: true }).click()
  await page.getByRole("button", { name: "Open Compass drawer", exact: true }).click()
  await page.getByRole("button", { name: "Pin Compass drawer open", exact: true }).click()
  const photo = page.getByRole("button", { name: "Edit sidebar photo", exact: true })
  await expect(photo).toBeVisible()
  const mobileSidebar = page.locator('[data-sidebar="sidebar"][data-mobile="true"]')
  const sidebarWidth = await mobileSidebar.evaluate((element) => element.getBoundingClientRect().width)
  expect(await photo.evaluate((element) => element.getBoundingClientRect().width)).toBeLessThan(sidebarWidth * 0.7)
  await page.getByRole("button", { name: "Projects", exact: true }).click()
  await page.waitForTimeout(200)
  await page.getByRole("button", { name: "Project Financials", exact: true }).click()
  const budget = page.getByRole("link", { name: "Project Budget", exact: true })
  await budget.scrollIntoViewIfNeeded()
  await expect.poll(() => budget.evaluate((element) => {
    const rect = element.getBoundingClientRect()
    return element.contains(document.elementFromPoint(rect.x + rect.width / 2, rect.y + rect.height / 2))
  })).toBe(true)
  await page.screenshot({ path: testInfo.outputPath("compact-mobile-financial-menu.png") })
})
