CREATE TABLE `greeting_card_requests` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`requested_by` text,
	`approved_by` text,
	`rejected_by` text,
	`released_by` text,
	`deleted_by` text,
	`provider` text DEFAULT 'handwrytten' NOT NULL,
	`delivery_method` text DEFAULT 'physical_mail' NOT NULL,
	`provider_order_id` text,
	`status` text DEFAULT 'pending_approval' NOT NULL,
	`provider_card_id` text NOT NULL,
	`card_name` text NOT NULL,
	`card_price_cents` integer,
	`recipient_type` text NOT NULL,
	`occasion` text,
	`message` text NOT NULL,
	`wishes` text NOT NULL,
	`recipient_first_name` text NOT NULL,
	`recipient_last_name` text NOT NULL,
	`recipient_business_name` text,
	`recipient_address1` text NOT NULL,
	`recipient_address2` text,
	`recipient_city` text NOT NULL,
	`recipient_state` text NOT NULL,
	`recipient_postal_code` text NOT NULL,
	`recipient_country` text DEFAULT 'United States' NOT NULL,
	`approval_note` text,
	`provider_error` text,
	`approved_at` text,
	`rejected_at` text,
	`released_at` text,
	`submitted_at` text,
	`cancelled_at` text,
	`deleted_at` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`requested_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`approved_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`rejected_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`released_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`deleted_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE INDEX `greeting_card_requests_org_status_created_idx` ON `greeting_card_requests` (`organization_id`,`status`,`created_at`);
--> statement-breakpoint
CREATE INDEX `greeting_card_requests_requester_created_idx` ON `greeting_card_requests` (`requested_by`,`created_at`);
